//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Nespe
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NespeEntityContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NespeEntityContainer object using the connection string found in the 'NespeEntityContainer' section of the application configuration file.
        /// </summary>
        public NespeEntityContainer() : base("name=NespeEntityContainer", "NespeEntityContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NespeEntityContainer object.
        /// </summary>
        public NespeEntityContainer(string connectionString) : base(connectionString, "NespeEntityContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NespeEntityContainer object.
        /// </summary>
        public NespeEntityContainer(EntityConnection connection) : base(connection, "NespeEntityContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
