//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nespe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\nespe-ncom-0.sdf")]
        public string Data {
            get {
                return ((string)(this["Data"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hqbusa0059\\SCInterface\\EUR\\CH\\1_New")]
        public string IT_XML_ELEBORATION_FOLDER {
            get {
                return ((string)(this["IT_XML_ELEBORATION_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://141.122.180.58/ReportServer/Pages/ReportViewer.aspx?/GLOBAL+SMR/SM+Ticket+Detail+List&rs:Command=Render&rs:parameterlanguage=en-US&rs:Format=XML&rc:Parameters=Collapsed&strRole=%25&strEmail=%25&strCrntAGSuprtOrg=%25&strOpenAGSuprtOrg=%25&strCrntAGTwr=%25&strOpenAGTwr=%25&strCrntAGOrgUnit=%25&strOpenAG=%25&strCategory=%25&strCrntPriority=%25&strEndUserImpact=%25&strStatus=%25&strAsgColaboration=%25&strConsoSrvcType=%25&strConsoSrvcName=%25&strAffEnv=%25&strAffCI=%25&strProcess=%25&paramExcelVer=True&strRowGrouping=CurrentAGSupportorg&strRowGrp1=%25&strRowGrp2=%25&strRowGrp3=%25&strGrpRow4=%25&strRowGrp5=%25&strChartView=%25&strChartCategory=%25&strActionType=%25&strConsolidatedSrvcGrp=%25&strConsolidatedSrvcFunc=%25&strBusOrg=%25&StrInitPriority=%25&strInterSuprtOrg=%25&strAlertStatus=%25&strTouched=%25&strIinteractions=%25&strOpenPeriod=%25&strMasterInteract=%25&strIMNum=%25&strSelectedbAG=%25&strCrntAG=CH_IT SUPPORT WKS_ORB INSTALLATION")]
        public string IT_VALIDATION_URL {
            get {
                return ((string)(this["IT_VALIDATION_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp")]
        public string IT_VALIDATION_TEMP_FOLDER {
            get {
                return ((string)(this["IT_VALIDATION_TEMP_FOLDER"]));
            }
        }
    }
}
