//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Nespe.Entities", "FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nespe.Department), "tbl_person_department", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nespe.PersonDepartment), true)]
[assembly: EdmRelationshipAttribute("Nespe.Entities", "FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Nespe.Person), "tbl_person_department", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nespe.PersonDepartment), true)]
[assembly: EdmRelationshipAttribute("Nespe.Entities", "FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Nespe.PersonDepartment), "tbl_request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Nespe.Request), true)]

#endregion

namespace Nespe
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NespeDbContextEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NespeDbContextEntities object using the connection string found in the 'NespeDbContextEntities' section of the application configuration file.
        /// </summary>
        public NespeDbContextEntities() : base("name=NespeDbContextEntities", "NespeDbContextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NespeDbContextEntities object.
        /// </summary>
        public NespeDbContextEntities(string connectionString) : base(connectionString, "NespeDbContextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NespeDbContextEntities object.
        /// </summary>
        public NespeDbContextEntities(EntityConnection connection) : base(connection, "NespeDbContextEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> tbl_department
        {
            get
            {
                if ((_tbl_department == null))
                {
                    _tbl_department = base.CreateObjectSet<Department>("tbl_department");
                }
                return _tbl_department;
            }
        }
        private ObjectSet<Department> _tbl_department;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> tbl_person
        {
            get
            {
                if ((_tbl_person == null))
                {
                    _tbl_person = base.CreateObjectSet<Person>("tbl_person");
                }
                return _tbl_person;
            }
        }
        private ObjectSet<Person> _tbl_person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PersonDepartment> tbl_person_department
        {
            get
            {
                if ((_tbl_person_department == null))
                {
                    _tbl_person_department = base.CreateObjectSet<PersonDepartment>("tbl_person_department");
                }
                return _tbl_person_department;
            }
        }
        private ObjectSet<PersonDepartment> _tbl_person_department;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Request> tbl_request
        {
            get
            {
                if ((_tbl_request == null))
                {
                    _tbl_request = base.CreateObjectSet<Request>("tbl_request");
                }
                return _tbl_request;
            }
        }
        private ObjectSet<Request> _tbl_request;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RequestTypeInfo> tbl_requestTypeInfo
        {
            get
            {
                if ((_tbl_requestTypeInfo == null))
                {
                    _tbl_requestTypeInfo = base.CreateObjectSet<RequestTypeInfo>("tbl_requestTypeInfo");
                }
                return _tbl_requestTypeInfo;
            }
        }
        private ObjectSet<RequestTypeInfo> _tbl_requestTypeInfo;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_department EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_department(Department department)
        {
            base.AddObject("tbl_department", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_person(Person person)
        {
            base.AddObject("tbl_person", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_person_department EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_person_department(PersonDepartment personDepartment)
        {
            base.AddObject("tbl_person_department", personDepartment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_request EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_request(Request request)
        {
            base.AddObject("tbl_request", request);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_requestTypeInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_requestTypeInfo(RequestTypeInfo requestTypeInfo)
        {
            base.AddObject("tbl_requestTypeInfo", requestTypeInfo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nespe.Entities", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Department CreateDepartment(global::System.Int64 id)
        {
            Department department = new Department();
            department.Id = id;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                OnSIDChanging(value);
                ReportPropertyChanging("SID");
                _SID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SID");
                OnSIDChanged();
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nespe.Entities", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Person CreatePerson(global::System.Int64 id, global::System.String firstName, global::System.String lastName)
        {
            Person person = new Person();
            person.Id = id;
            person.FirstName = firstName;
            person.LastName = lastName;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SID
        {
            get
            {
                return _SID;
            }
            set
            {
                OnSIDChanging(value);
                ReportPropertyChanging("SID");
                _SID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SID");
                OnSIDChanged();
            }
        }
        private global::System.String _SID;
        partial void OnSIDChanging(global::System.String value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Initials
        {
            get
            {
                return _Initials;
            }
            set
            {
                OnInitialsChanging(value);
                ReportPropertyChanging("Initials");
                _Initials = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Initials");
                OnInitialsChanged();
            }
        }
        private global::System.String _Initials;
        partial void OnInitialsChanging(global::System.String value);
        partial void OnInitialsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nespe.Entities", Name="PersonDepartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonDepartment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PersonDepartment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rank">Initial value of the Rank property.</param>
        /// <param name="department_Id">Initial value of the Department_Id property.</param>
        /// <param name="person_Id">Initial value of the Person_Id property.</param>
        public static PersonDepartment CreatePersonDepartment(global::System.Int64 id, global::System.Int64 rank, global::System.Int64 department_Id, global::System.Int64 person_Id)
        {
            PersonDepartment personDepartment = new PersonDepartment();
            personDepartment.Id = id;
            personDepartment.Rank = rank;
            personDepartment.Department_Id = department_Id;
            personDepartment.Person_Id = person_Id;
            return personDepartment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.Int64 _Rank;
        partial void OnRankChanging(global::System.Int64 value);
        partial void OnRankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Department_Id
        {
            get
            {
                return _Department_Id;
            }
            set
            {
                OnDepartment_IdChanging(value);
                ReportPropertyChanging("Department_Id");
                _Department_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Department_Id");
                OnDepartment_IdChanged();
            }
        }
        private global::System.Int64 _Department_Id;
        partial void OnDepartment_IdChanging(global::System.Int64 value);
        partial void OnDepartment_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Person_Id
        {
            get
            {
                return _Person_Id;
            }
            set
            {
                OnPerson_IdChanging(value);
                ReportPropertyChanging("Person_Id");
                _Person_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Person_Id");
                OnPerson_IdChanged();
            }
        }
        private global::System.Int64 _Person_Id;
        partial void OnPerson_IdChanging(global::System.Int64 value);
        partial void OnPerson_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _Role;
        partial void OnRoleChanging(Nullable<global::System.Int32> value);
        partial void OnRoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Nespe.Entities", "FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_department_Department_Id", "tbl_department", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Nespe.Entities", "FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("Nespe.Entities.FK_dbo_tbl_person_department_dbo_tbl_person_Person_Id", "tbl_person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nespe.Entities", Name="Request")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Request : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Request object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="employeeNumber">Initial value of the EmployeeNumber property.</param>
        /// <param name="nonSAP">Initial value of the nonSAP property.</param>
        /// <param name="completed">Initial value of the Completed property.</param>
        /// <param name="activeDirectoryId">Initial value of the ActiveDirectoryId property.</param>
        public static Request CreateRequest(global::System.Int64 id, global::System.DateTime startDate, global::System.String employeeNumber, global::System.Boolean nonSAP, global::System.Boolean completed, global::System.String activeDirectoryId)
        {
            Request request = new Request();
            request.Id = id;
            request.StartDate = startDate;
            request.EmployeeNumber = employeeNumber;
            request.nonSAP = nonSAP;
            request.Completed = completed;
            request.ActiveDirectoryId = activeDirectoryId;
            return request;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PersonDepartment_Id
        {
            get
            {
                return _PersonDepartment_Id;
            }
            set
            {
                OnPersonDepartment_IdChanging(value);
                ReportPropertyChanging("PersonDepartment_Id");
                _PersonDepartment_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersonDepartment_Id");
                OnPersonDepartment_IdChanged();
            }
        }
        private Nullable<global::System.Int64> _PersonDepartment_Id;
        partial void OnPersonDepartment_IdChanging(Nullable<global::System.Int64> value);
        partial void OnPersonDepartment_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Function
        {
            get
            {
                return _Function;
            }
            set
            {
                OnFunctionChanging(value);
                ReportPropertyChanging("Function");
                _Function = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Function");
                OnFunctionChanged();
            }
        }
        private global::System.String _Function;
        partial void OnFunctionChanging(global::System.String value);
        partial void OnFunctionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Superior
        {
            get
            {
                return _Superior;
            }
            set
            {
                OnSuperiorChanging(value);
                ReportPropertyChanging("Superior");
                _Superior = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Superior");
                OnSuperiorChanged();
            }
        }
        private global::System.String _Superior;
        partial void OnSuperiorChanging(global::System.String value);
        partial void OnSuperiorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BusinessStream
        {
            get
            {
                return _BusinessStream;
            }
            set
            {
                OnBusinessStreamChanging(value);
                ReportPropertyChanging("BusinessStream");
                _BusinessStream = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BusinessStream");
                OnBusinessStreamChanged();
            }
        }
        private global::System.String _BusinessStream;
        partial void OnBusinessStreamChanging(global::System.String value);
        partial void OnBusinessStreamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeNumber
        {
            get
            {
                return _EmployeeNumber;
            }
            set
            {
                OnEmployeeNumberChanging(value);
                ReportPropertyChanging("EmployeeNumber");
                _EmployeeNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmployeeNumber");
                OnEmployeeNumberChanged();
            }
        }
        private global::System.String _EmployeeNumber;
        partial void OnEmployeeNumberChanging(global::System.String value);
        partial void OnEmployeeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean nonSAP
        {
            get
            {
                return _nonSAP;
            }
            set
            {
                OnnonSAPChanging(value);
                ReportPropertyChanging("nonSAP");
                _nonSAP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nonSAP");
                OnnonSAPChanged();
            }
        }
        private global::System.Boolean _nonSAP;
        partial void OnnonSAPChanging(global::System.Boolean value);
        partial void OnnonSAPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransFrom
        {
            get
            {
                return _TransFrom;
            }
            set
            {
                OnTransFromChanging(value);
                ReportPropertyChanging("TransFrom");
                _TransFrom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransFrom");
                OnTransFromChanged();
            }
        }
        private global::System.String _TransFrom;
        partial void OnTransFromChanging(global::System.String value);
        partial void OnTransFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parrain
        {
            get
            {
                return _Parrain;
            }
            set
            {
                OnParrainChanging(value);
                ReportPropertyChanging("Parrain");
                _Parrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parrain");
                OnParrainChanged();
            }
        }
        private global::System.String _Parrain;
        partial void OnParrainChanging(global::System.String value);
        partial void OnParrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private global::System.Boolean _Completed;
        partial void OnCompletedChanging(global::System.Boolean value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActiveDirectoryId
        {
            get
            {
                return _ActiveDirectoryId;
            }
            set
            {
                OnActiveDirectoryIdChanging(value);
                ReportPropertyChanging("ActiveDirectoryId");
                _ActiveDirectoryId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActiveDirectoryId");
                OnActiveDirectoryIdChanged();
            }
        }
        private global::System.String _ActiveDirectoryId;
        partial void OnActiveDirectoryIdChanging(global::System.String value);
        partial void OnActiveDirectoryIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Nespe.Entities", "FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department")]
        public PersonDepartment PersonDepartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonDepartment>("Nespe.Entities.FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonDepartment>("Nespe.Entities.FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PersonDepartment> PersonDepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonDepartment>("Nespe.Entities.FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PersonDepartment>("Nespe.Entities.FK_dbo_tbl_request_dbo_tbl_person_department_PersonDepartment_Id", "tbl_person_department", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Nespe.Entities", Name="RequestTypeInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RequestTypeInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RequestTypeInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static RequestTypeInfo CreateRequestTypeInfo(global::System.Int64 id)
        {
            RequestTypeInfo requestTypeInfo = new RequestTypeInfo();
            requestTypeInfo.Id = id;
            return requestTypeInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }

    #endregion
    
}
